"""AST and Python source code generator for compiled agent trajectories."""

from __future__ import annotations

import ast
from typing import Any, Callable, Dict, List, Optional

from agentjit.types import (
    CompilationResult,
    ExecutionNode,
    Guard,
    Trajectory,
    ValueSource,
)


class GuardViolation(Exception):
    """Raised at runtime when a compiled pipeline's speculative guard fails."""
    def __init__(self, message: str, param: str = "") -> None:
        super().__init__(message)
        self.param = param


class CodeGenerator:
    """Synthesizes human-readable, typed, and executable Python code from an execution DAG."""

    def __init__(
        self,
        entry_params: List[str],
        nodes: List[ExecutionNode],
        guards: List[Guard],
        final_source: ValueSource,
        tool_registry: Dict[str, Callable],
        func_name: str = "compiled_pipeline",
    ) -> None:
        self.entry_params = entry_params
        self.nodes = nodes
        self.guards = guards
        self.final_source = final_source
        self.tool_registry = tool_registry
        self.func_name = func_name

    def generate_source(self) -> str:
        """Generate formatted Python source code for the compiled pipeline."""
        lines: List[str] = []
        params_str = ", ".join(self.entry_params)
        lines.append(f"def {self.func_name}({params_str}):")
        lines.append('    """JIT-compiled trajectory pipeline generated by AgentJIT.')
        lines.append("    Executes deterministically in sub-millisecond time with zero token cost.")
        lines.append('    """')

        # 1. Speculative Guards
        if self.guards:
            lines.append("    # --- Speculative Guards ---")
            for g in self.guards:
                # Add validation statement
                lines.append(f"    if not ({g.condition_code}):")
                escaped_desc = g.description.replace('"', '\\"')
                lines.append(
                    f'        raise GuardViolation("{escaped_desc}", param="{g.target_param}")'
                )

        lines.append("")
        lines.append("    # --- Execution Steps ---")
        var_map: Dict[int, str] = {}

        # 2. Tool invocations
        for node in self.nodes:
            var_name = node.output_var_name
            var_map[node.node_id] = var_name

            args_parts: List[str] = []
            for param_k, val_src in node.argument_bindings.items():
                arg_expr = val_src.render_expression(var_map)
                args_parts.append(f"{param_k}={arg_expr}")

            args_str = ", ".join(args_parts)
            lines.append(
                f"    {var_name} = _tools[{repr(node.tool_name)}]({args_str})"
            )

        # 3. Final return
        lines.append("")
        lines.append("    # --- Return Final Result ---")
        return_expr = self.final_source.render_expression(var_map)
        lines.append(f"    return {return_expr}")

        return "\n".join(lines)

    def compile(self) -> CompilationResult:
        """Generate source code, validate AST, and compile into an executable callable."""
        source = self.generate_source()

        # Validate syntax via AST
        try:
            tree = ast.parse(source)
        except SyntaxError as e:
            return CompilationResult(
                success=False,
                source_code=source,
                error=f"Syntax error in synthesized code: {e}",
            )

        # Execute compilation in controlled namespace
        exec_globals: Dict[str, Any] = {
            "_tools": self.tool_registry,
            "GuardViolation": GuardViolation,
            "isinstance": isinstance,
            "int": int,
            "float": float,
            "str": str,
            "bool": bool,
            "dict": dict,
            "list": list,
        }
        exec_locals: Dict[str, Any] = {}

        try:
            code_obj = compile(tree, filename="<agentjit_compiled>", mode="exec")
            exec(code_obj, exec_globals, exec_locals)
            compiled_func = exec_locals.get(self.func_name)
        except Exception as e:
            return CompilationResult(
                success=False,
                source_code=source,
                error=f"Execution error during module compilation: {e}",
            )

        return CompilationResult(
            success=True,
            source_code=source,
            compiled_callable=compiled_func,
            nodes=self.nodes,
            guards=self.guards,
            entry_parameters=self.entry_params,
            output_expression=self.final_source.render_expression({}),
        )
